name: Update Score Tables
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yaml
          pip install json
      - name: Retrieve Skater Information
        run: python retrieve_and_convert_information.py
      - name: Update HTML
        run: python generate_html.py
      - name: Push Repo
        run: |
          git config user.name TheShak55
          git add .
          git commit -m "Updated Skater Information and Tables"
          git push
          
            
